# Generated by Django 3.1.7 on 2021-03-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Id',
            new_name='TeamId',
        ),
    ]
