# Generated by Django 3.1.7 on 2021-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0004_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamId', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Size', models.IntegerField()),
                ('Goal', models.IntegerField()),
                ('Realized', models.IntegerField()),
            ],
        ),
    ]
